fruits=["apple","mango","banana"]
mixed=["apple","mango",34]
print(fruits)
print(mixed)
print(fruits[1])
#print(fruits[3])
numbers=[2,15,11,7]
print(numbers)
numbers.sort()
print(numbers)
print(numbers.sort())
numbers.reverse()
print(numbers)
print(numbers[1:3])
print(numbers)
print(len(numbers))
print(max(numbers))
print(min(numbers))
numbers.append(8)
numbers.insert(1,23)
numbers.append(8)
print(numbers)
numbers.remove(8)
print(numbers)
numbers.pop()
print(numbers)
tp=(1)
# tp[0]=2 #error we cant change tuple
print(tp)
tp1=(1,)
print(tp1)
a=1
b=2
a,b=b,a
print(a,b)
